/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package os_1_task_4;

import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author root
 */
public class Choose_directory_panel extends javax.swing.JPanel {

    public static boolean check = false;
    public String current_directory_path;
    public static String selected_directory_path;
    Full_GUI fullGUI;
    /**
     * Creates new form panel1
     */

    /**
     * Creates new form Choose_directory_panel
     */
    JFileChooser chooser;
    String chooser_title;

    public Choose_directory_panel(Full_GUI aThis) {
        fullGUI = aThis;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        select_directory_panel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        directory_chooser_btn = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Gillius ADF", 1, 18)); // NOI18N
        jLabel1.setText("Select a Directory: ");

        directory_chooser_btn.setText("Directory Chooser");
        directory_chooser_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                directory_chooser_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout select_directory_panelLayout = new javax.swing.GroupLayout(select_directory_panel);
        select_directory_panel.setLayout(select_directory_panelLayout);
        select_directory_panelLayout.setHorizontalGroup(
            select_directory_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(select_directory_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(67, 67, 67)
                .addComponent(directory_chooser_btn)
                .addContainerGap())
        );
        select_directory_panelLayout.setVerticalGroup(
            select_directory_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(select_directory_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(select_directory_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(directory_chooser_btn))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addComponent(select_directory_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(104, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(178, 178, 178)
                .addComponent(select_directory_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(279, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void directory_chooser_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_directory_chooser_btnActionPerformed
        // TODO add your handling code here:
        chooser = new JFileChooser();
        chooser.setCurrentDirectory(new java.io.File("/home/root/"));
        chooser.setDialogTitle(chooser_title);
        chooser.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);
        if (chooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            check = true;
            current_directory_path = String.valueOf(chooser.getCurrentDirectory());
            selected_directory_path = String.valueOf(chooser.getSelectedFile());

            this.fullGUI.cardLayout.show(this.fullGUI.container, "MENU_PANEL");

        } else {
            JOptionPane.showMessageDialog(null, "No Directory selected!");
        }
    }//GEN-LAST:event_directory_chooser_btnActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton directory_chooser_btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel select_directory_panel;
    // End of variables declaration//GEN-END:variables
}
