/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package os_1_task_4;

/**
 *
 * @author root
 */
public class Menu_panel extends javax.swing.JPanel {
    Full_GUI fullGUI;
    /**
     * Creates new form panel2
     */
    public Menu_panel(Full_GUI aThis) {
        fullGUI = aThis;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        list_btn = new javax.swing.JButton();
        change_permissions_btn = new javax.swing.JButton();
        make_files_btn = new javax.swing.JButton();
        delete_files_btn = new javax.swing.JButton();
        create_shortcut_btn = new javax.swing.JButton();
        make_directory_btn = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        list_btn.setText("List Files/Directories");
        list_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                list_btnActionPerformed(evt);
            }
        });

        change_permissions_btn.setText("Change Permissions of files");
        change_permissions_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                change_permissions_btnActionPerformed(evt);
            }
        });

        make_files_btn.setText("Make File");
        make_files_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                make_files_btnActionPerformed(evt);
            }
        });

        delete_files_btn.setText("Delete File");
        delete_files_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_files_btnActionPerformed(evt);
            }
        });

        create_shortcut_btn.setText("Create symbolic link files");
        create_shortcut_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                create_shortcut_btnActionPerformed(evt);
            }
        });

        make_directory_btn.setText("Make Directory");
        make_directory_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                make_directory_btnActionPerformed(evt);
            }
        });

        jButton1.setText("Delete Directory");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Back to directory chooser");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(85, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(list_btn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(create_shortcut_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(change_permissions_btn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(delete_files_btn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                            .addComponent(make_files_btn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(make_directory_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE)))
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(75, 75, 75))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(list_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(change_permissions_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(make_files_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(make_directory_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(delete_files_btn, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(39, 39, 39)
                .addComponent(create_shortcut_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addContainerGap(38, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void list_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_list_btnActionPerformed
 
        //yroo7 3la list_panel
        this.fullGUI.cardLayout.show(this.fullGUI.container,"LIST_PANEL");
    }//GEN-LAST:event_list_btnActionPerformed

    private void change_permissions_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_change_permissions_btnActionPerformed
            // hyroo7 3la change_permiaaion_panel
        this.fullGUI.cardLayout.show(this.fullGUI.container,"CHANGE_PERMISSION");
    }//GEN-LAST:event_change_permissions_btnActionPerformed

    private void make_files_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_make_files_btnActionPerformed
        // hayro7 3la make_file_panel4
        this.fullGUI.cardLayout.show(this.fullGUI.container, "MAKE_FILE");
    }//GEN-LAST:event_make_files_btnActionPerformed

    private void make_directory_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_make_directory_btnActionPerformed
        // TODO add your handling code here:
        this.fullGUI.cardLayout.show(this.fullGUI.container, "MAKE_DIRECTORY");
    }//GEN-LAST:event_make_directory_btnActionPerformed

    private void delete_files_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_files_btnActionPerformed
        // TODO add your handling code here:
        this.fullGUI.cardLayout.show(this.fullGUI.container, "DELETE_FILE");
    }//GEN-LAST:event_delete_files_btnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.fullGUI.cardLayout.show(this.fullGUI.container, "DELETE_DIRECTORY");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void create_shortcut_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_create_shortcut_btnActionPerformed
        // TODO add your handling code here:
        this.fullGUI.cardLayout.show(this.fullGUI.container, "CREATE_SHORTCUT");
    }//GEN-LAST:event_create_shortcut_btnActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.fullGUI.cardLayout.show(this.fullGUI.container,"CHOOSE_DIRECTORY");
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton change_permissions_btn;
    private javax.swing.JButton create_shortcut_btn;
    private javax.swing.JButton delete_files_btn;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton list_btn;
    private javax.swing.JButton make_directory_btn;
    private javax.swing.JButton make_files_btn;
    // End of variables declaration//GEN-END:variables
}
